[install]
optional = true
dev = true
peer = true
production = false
exact = false
auto = "auto"
registry = "https://registry.npmjs.org"

[install.lockfile]
save = true

[dependencies]

[run]
shell = "bun" # default outside of Windows

[build]
minify = true
target = "esnext"

[test]
root = "./__tests__"
coverage = true
# coverageThreshold = 0.9
